(* generated by dune *)

(** @canonical Time_unix.Import *)
module Import = Time_unix__Import

(** @canonical Time_unix.Time_functor *)
module Time_functor = Time_unix__Time_functor

(** @canonical Time_unix.Time_functor_intf *)
module Time_functor_intf = Time_unix__Time_functor_intf
