(* generated by dune *)

(** @canonical Interval_lib.Interval *)
module Interval = Interval_lib__Interval

(** @canonical Interval_lib.Interval_intf *)
module Interval_intf = Interval_lib__Interval_intf
