(** File generated by nikhil *)
Require Import ExtrOcamlNatInt.
From QuickChick Require Import QuickChick.
QCDune "dune".

Inductive tree : Set :=
| E : tree
| T : tree -> nat -> nat -> tree -> tree.
Axiom prop_InsertPost2 : tree -> nat -> nat -> nat -> bool .
Derive (Show, Arbitrary) for tree.
Extract Inductive tree => "Impl.tree"
  [
    "Impl.E"
    "Impl.T"
  ].
Extract Constant prop_InsertPost2 => "Impl.prop_InsertPost2".
QCInclude "/Users/nikhil/Code/Research/etna/workloads/OCaml/BST/lib/impl.ml".
QCInclude "/Users/nikhil/Code/Research/etna/workloads/OCaml/BST/lib/Strategies/nat.ml".
QuickChick prop_InsertPost2.
